title: shingkong 
description: nothing but test

markdown: rdiscount

social:
  - title: GitHub
    img: /assets/images/github.ico
    url: https://github.com/shingkong
  - title: V2EX
    img: /assets/images/v2ex.png
    url: https://www.v2ex.com/member/shingkong
  - title: Blog
    img: /assets/images/avatar.png
    url: http://shingkong.com
  - title: Twitter
    img: /assets/images/twitter.ico
    url: https://twitter.com/shingkongx
  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:lingshing#gmail.com

avatar: /assets/images/avatar.png
introduction: >

~Theme: jekyll-theme-minimal
